---
- name: make path for private key
  file:
    path: "/etc/ssl/private"
    state: directory
    mode: '0700'

- name: place private key
  copy:
    src: ./files/private.key
    dest: "/etc/ssl/private/private.key"

- name: place cert
  copy:
    src: ./files/public.crt
    dest: "/etc/ssl/certs/public.crt"

- name: place nginx kaholo config file
  template:
    src: ./templates/kaholo.conf
    dest: "/etc/nginx/sites-available/kaholo"

- name: symlink ln -s /etc/nginx/sites-available/kaholo /etc/nginx/sites-enabled/kaholo
  file:
    src: /etc/nginx/sites-available/kaholo
    dest: /etc/nginx/sites-enabled/kaholo
    state: link

- name: Remove Default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: restart nginx
  service:
    name: "nginx"
    enabled: "yes"
    state: "restarted"
