---
- name: Install ufw
  apt:
    package: ufw
    state: present

- name: Configure ufw rules
  ufw:
    rule: '{{ item.rule }}'
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  with_items:
    - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }

- name: Start and enable firewall (ufw)
  ufw:
    state: enabled

# - name: Leave firewall disabled
#   ufw:
#     state: disabled
