---
- hosts: kaholo
  roles:
  - { role: ubuntu22, become: true }
  - { role: microk8s, become: false }
  - { role: kaholohelm, become: false }
  vars_files:
  - vars/kaholo.yml
  - vars/secrets.yml
  # - vars/kaholo-b.yml
  # - vars/secrets-demo.yml