---
- name: snap install helm --classic
  snap:
    name: helm
    classic: true
  become: true

- name: Unzip Kaholo Helm Project
  unarchive:
    src: ./files/kaholo-helm.zip
    dest: ~/
    creates: ~/kaholo-helm

- name: Loosen up default network policy
  lineinfile:
    path: ~/kaholo-helm/values.yaml
    search_string: allowPotentialCommandInjectionK8S
    line: '  allowPotentialCommandInjectionK8S: true'

- name: Place public license key
  copy:
    src: ./files/kaholo-license.pub
    dest: ~/kaholo-helm/kaholo-license.pub

- name: Get all the scripts in tenants management
  find:
    paths: ~/kaholo-helm/scripts/tenants-management
  register: tenant_scripts

- name: Add aliases expansion option to scripts
  lineinfile:
    path: "{{ item.path }}"
    line: shopt -s expand_aliases
    insertafter: '^#!/bin/bash'
  with_items: "{{ tenant_scripts.files }}"

- name: Add alias kubectl="microk8s kubectl" to scripts
  lineinfile:
    path: "{{ item.path }}"
    line: alias kubectl="microk8s kubectl"
    insertafter: '^shopt -s expand_aliases'
  with_items: "{{ tenant_scripts.files }}"

- name: Add environment variable to scripts to help helm find kubernetes
  lineinfile:
    path: "{{ item.path }}"
    line: export KUBECONFIG=/var/snap/microk8s/current/credentials/client.config
    insertafter: '^alias kubectl'
  with_items: "{{ tenant_scripts.files }}"

- name: Create Namespace
  command:
    cmd: microk8s kubectl create namespace {{ mk8s_namespace }}
    creates: ~/ansible_temp/namespace.created

- name: Create Docker Kubernetes Secret
  command:
    cmd: microk8s kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=matankaholo --docker-password={{ dckr_pat }} --docker-email=poc.user@kaholo.io -n {{ mk8s_namespace }}
    creates: ~/ansible_temp/namespace.created

- name: Record success creating namespace
  file:
    path: ~/ansible_temp/namespace.created
    state: touch

- name: Run TENANT_INSTALL script
  shell:
    chdir: ~/kaholo-helm/scripts/tenants-management/
    cmd: |
      ./TENANT_INSTALL.sh \
      -t {{ kaholo_imagetag }} \
      -n {{ mk8s_namespace }} \
      -d {{ domain }} \
      -s {{ host }} \
      -o microk8s-hostpath \
      -x microk8s-hostpath \
      -k {{ kaholo_server_key }} \
      -u '{{ agent_resources }}' \
      -b
    creates: ~/kaholo-helm/values-{{ mk8s_namespace }}.yaml
