---
# - name: Clone Kaholo Helm Charts
#   git:
#     repo: https://github.com/Kaholo/kaholo-helm.git
#     dest: ~/kaholo-helm
#     clone: yes
#     update: no

- name: snap install helm --classic
  snap:
    name: helm
    classic: true
  become: true

- name: Unzip Kaholo Helm Project
  unarchive:
    src: ./files/kaholo-helm-main.zip
    dest: ~/
    creates: ~/kaholo-helm-main

- name: Place public license key
  copy:
    src: ./files/kaholo-license.pub
    dest: ~/kaholo-helm-main/kaholo-license.pub

- name: Get all the scripts in tenants management
  find:
    paths: ~/kaholo-helm-main/scripts/tenants-management
  register: tenant_scripts

- name: Add aliases expansion option to script
  lineinfile:
    path: "{{ item.path }}"
    line: shopt -s expand_aliases
    insertafter: '^#!/bin/bash'
  with_items: "{{ tenant_scripts.files }}"

- name: Add alias kubectl="microk8s kubectl"
  lineinfile:
    path: "{{ item.path }}"
    line: alias kubectl="microk8s kubectl"
    insertafter: '^shopt -s expand_aliases'
  with_items: "{{ tenant_scripts.files }}"

- name: Add environment variable for helm to find kubernetes
  lineinfile:
    path: "{{ item.path }}"
    line: export KUBECONFIG=/var/snap/microk8s/current/credentials/client.config
    insertafter: '^alias kubectl'
  with_items: "{{ tenant_scripts.files }}"

- name: Create Namespace
  command:
    cmd: microk8s kubectl create namespace kaholo-poc
    creates: ~/namespace.created

- name: Record success creating namespace
  file:
    path: ~/namespace.created
    state: touch

- name: Create Docker Kubernetes Secret
  command:
    cmd: microk8s kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=matankaholo --docker-password={{ docker_password }} --docker-email={{ docker_email }} -n kaholo-poc

- name: Run TENANT_INSTALL script
  shell:
    chdir: ~/kaholo-helm-main/scripts/tenants-management/
    cmd: |
      ./TENANT_INSTALL.sh \
      -t {{ kaholo_imagetag }} \
      -n poc \
      -d kaholodemo.net \
      -s kaholo-d \
      -o microk8s-hostpath \
      -k '{{ kaholo_server_key }}' \
      -f -b
    creates: ~/kaholo-helm-main/values-poc.yaml
