---
- include_tasks: helm.yml
- include_tasks: rekeyingress_provided.yml
  when: rekey_ingress == "provided"
- include_tasks: rekeyingress_letsencrypt.yml
  when: rekey_ingress == "letsencrypt"
- include_tasks: results.yml
