---
- name: Copy TLS certificate
  copy:
    src: ../files/public.crt
    dest: ~/ansible_temp/public.crt

- name: Copy TLS key
  copy:
    src: ../files/private.key
    dest: ~/ansible_temp/private.key

- name: Create secret {{ mk8s_namespace }}-tls
  command:
    cmd: microk8s kubectl create secret tls {{ mk8s_namespace }}-tls --cert=ansible_temp/public.crt --key=ansible_temp/private.key -n {{ mk8s_namespace }}
    creates: ~/ansible_temp/tls-secret.created

- name: Record success creating secret
  file:
    path: ~/ansible_temp/tls-secret.created
    state: touch

- name: Overwrite key for security reasons
  copy:
    src: ../files/public.crt
    dest: ~/ansible_temp/private.key

- name: Delete key for security reasons
  file:
    path: ~/ansible_temp/private.key
    state: absent

- name: Tell Ingress {{ mk8s_namespace }}.{{ domain }} to use new secret
  command:
    cmd: "microk8s kubectl -n {{ mk8s_namespace }} patch ingress {{ mk8s_namespace }}.{{ domain }} --type=json -p='[{\"op\": \"add\", \"path\": \"/spec/tls/0/secretName\", \"value\": \"{{ mk8s_namespace }}-tls\"}]'"
    creates: ~/ansible_temp/ingress-rekey.done

- name: Record success rekeying ingress
  file:
    path: ~/ansible_temp/ingress-rekey.done
    state: touch

