---
- name: copy over Kaholo control scripts
  copy:
    src: ./scripts/
    dest: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: a+x
    directory_mode: yes

- name: copy over Kaholo image list and project tarball
  copy:
    src: ./files/
    dest: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    directory_mode: yes

- name: extract the kaholo-enterprise project
  unarchive:
    src: /home/ubuntu/kaholo-enterprise.tgz
    dest: /home/ubuntu/
    remote_src: yes
    creates: /home/ubuntu/kaholo-enterprise