apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ mk8s_namespace }}-tls
  namespace: {{ mk8s_namespace }}
spec:
  secretName: {{ mk8s_namespace }}-tls
  duration: 2160h
  renewBefore: 360h
  commonName: {{ host }}.{{ domain }}
  dnsNames:
  - {{ host }}.{{ domain }}
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
